trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples
    - repository: bulkUpload
      type: github
      name: osisoft/sample-adh-bulk_upload-dotnet
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: SDSDataViewJupyter

jobs:
  - job: Tests
    strategy:
      maxParallel: 1 # Avoid conflicts in ADH
      matrix:
        linux:
          agentOS: Linux
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    variables:
      - name: NamespaceId
        value: Derek
    steps:
      - checkout: self
        path: 's'
      - checkout: bulkUpload
        path: 's/bu'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'pip install requests'
          workingDirectory: '$(Build.SourcesDirectory)'
        condition: eq(variables['agentOS'], 'Windows_NT')
        displayName: Install Requests

      - task: PowerShell@2
        inputs:
          filePath: '$(Build.SourcesDirectory)/configure_cert.ps1'
        condition: eq(variables['agentOS'], 'Windows_NT')
        displayName: 'Configure Umbrella Certificate'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, ClientId, ClientSecret, Resource'

      - script: |
          echo Clean
          dotnet clean
          echo Build
          dotnet build
        workingDirectory: $(Build.SourcesDirectory)/bu/BulkUploader
        displayName: 'Build BulkUploader'

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/bu/SampleCollections/DataViewWind/Data
          contents: '**'
          targetFolder: $(Build.SourcesDirectory)/bu/BulkUploader/Data
        displayName: 'Copy bulk data files'
        condition: eq('$(upload)', true)

      - script: dotnet run
        workingDirectory: $(Build.SourcesDirectory)/bu/BulkUploader
        displayName: 'Upload data needed'
        condition: eq('$(upload)', true)

      - script: |
          echo Install requirements
          pip install -r requirements.txt
          echo Install test tools
          pip install -r test-requirements.txt
          echo Export notebook
          python -m jupyter nbconvert --to script Wind_Turbine_ADH_Data_ADH_Python_Library.ipynb
          echo Run tests
          python -m pytest --junit-xml=junit/test-results.xml ./Wind_Turbine_ADH_Data_ADH_Python_Library.py
          echo Complete
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          searchFolder: '$(Build.SourcesDirectory)'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - script: |
            pip install nbconvert
            jupyter nbconvert --to script Wind_Turbine_ADH_Data_ADH_Python_Library.ipynb
      useRequirementsTxt: true
