trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples
    - repository: bulkUpload
      type: github
      name: osisoft/sample-ocs-bulk_upload-dotnet
      endpoint: osisoft/OSI-Samples
      ref: pipelines

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.sds_python.ini
  - name: bulkUploadCredFile
    value: appsettings.json
  - name: bulkUploadCredFileLibrary
    value: product-readiness.BulkUpload_DataViewWindFarm.json
  - name: analysisProject
    value: SDSDataViewJupyter

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          agentOS: Linux
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    steps:
      - checkout: self
        path: 's'
      - checkout: bulkUpload
        path: 's/bu'

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(bulkUploadCredFile)
          fileLibrary: $(bulkUploadCredFileLibrary)
          filePath: /bu/BulkUploader

      - script: |
          echo Clean
          dotnet clean
          echo Build
          dotnet build
        workingDirectory: $(Build.SourcesDirectory)/bu/BulkUploader
        displayName: 'Build BulkUploader'

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/bu/SampleCollections/DataViewWind/Data
          contents: '**'
          targetFolder: $(Build.SourcesDirectory)/bu/BulkUploader/Data
        displayName: 'Copy bulk data files'

      - script: dotnet run
        workingDirectory: $(Build.SourcesDirectory)/bu/BulkUploader
        displayName: 'Upload data needed'

      - script: |
          echo Install requirements
          pip install -r requirements.txt
          echo Install test tools
          pip install -r test-requirements.txt
          echo Run tests
          jupyter nbconvert --to script Wind_Turbine_OCS_Data_OCS_Python_Library.ipynb
          python -m pytest --junitxml=junit/test-results.xml ./Wind_Turbine_OCS_Data_OCS_Python_Library.py
          echo Complete
        displayName: 'Run tests'

      #      - script: dotnet run delete
      #        workingDirectory: $(Build.SourcesDirectory)/BulkUploader
      #        displayName: 'Clean up data'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          searchFolder: '$(Build.SourcesDirectory)'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
        parameters:
          skip: eq(variables['Agent.OS'], 'Linux')
          useRequirementsTxt: true
